### ISSUE TITLE
Whisper Model

### ISSUE THREAD

**Issue by ojixzzz** [Reinjin/Quranku_BE#1]
ijin pakai datasetnya mas,
datasetnya saya coba finetuning ke model whisper hasilnya cukup memuaskan

https://huggingface.co/ojisetyawan/whisper-base-ar-quran-ft-hijaiyah-2
https://huggingface.co/spaces/ojisetyawan/Whisper-Hijaiyah-Quran

**Comment by Reinjin** [comment]
siap.., silahkan kak, maaf baru lihat, kemarin udah di HF
